// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-yGFQtGhU5Tp73MNWUg3XRWP3J0Nvms',
    appId: '1:193516396834:web:75d73fa699cec32493457b',
    messagingSenderId: '193516396834',
    projectId: 'cozy-session',
    authDomain: 'cozy-session.firebaseapp.com',
    storageBucket: 'cozy-session.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5LqZ5IMDZLEnNc_xI138vquhDGVt5iD4',
    appId: '1:193516396834:android:47c8f4e8ff37ba8693457b',
    messagingSenderId: '193516396834',
    projectId: 'cozy-session',
    storageBucket: 'cozy-session.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-cwjigNrrtZIbw_ho0ZCqAgD_FYoqmnI',
    appId: '1:193516396834:ios:adf1906b9d5c256693457b',
    messagingSenderId: '193516396834',
    projectId: 'cozy-session',
    storageBucket: 'cozy-session.firebasestorage.app',
    iosBundleId: 'com.diaa.cozysession.cozySession',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-cwjigNrrtZIbw_ho0ZCqAgD_FYoqmnI',
    appId: '1:193516396834:ios:adf1906b9d5c256693457b',
    messagingSenderId: '193516396834',
    projectId: 'cozy-session',
    storageBucket: 'cozy-session.firebasestorage.app',
    iosBundleId: 'com.diaa.cozysession.cozySession',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV-yGFQtGhU5Tp73MNWUg3XRWP3J0Nvms',
    appId: '1:193516396834:web:191dbe17d310a69a93457b',
    messagingSenderId: '193516396834',
    projectId: 'cozy-session',
    authDomain: 'cozy-session.firebaseapp.com',
    storageBucket: 'cozy-session.firebasestorage.app',
  );
}
